### ISSUE TITLE
code readability

### ISSUE THREAD

**Issue by schmurfy** [Amaury/FineDB#1]
is there a reason for things like:

``` c
#define PP_write_int(tag, type) \
      check_min_max_of_type(num, type)? write_int_with_tag<tag, type>(M, out, num):

// ...

case MRB_TT_FIXNUM: {
  mrb_int const num = mrb_fixnum(v);
  return
      (-32 <= num and num <= 0x7f)? write_int<uint8_t>(M, out, num & 0xff):
      (num >= 0)? (
          PP_write_int(0xCC, uint8_t)
          PP_write_int(0xCD, uint16_t)
          PP_write_int(0xCE, uint32_t)
          PP_write_int(0xCF, uint64_t)
          range_error):
      PP_write_int(0xD0, int8_t)
      PP_write_int(0xD1, int16_t)
      PP_write_int(0xD2, int32_t)
      PP_write_int(0xD3, int64_t)
      range_error;
}

```

That is surely well placed in the worst code I had to read :)

I don't write C/C++ on a  daily basis but I suppose today's compilers are more that capable of optimizing things without having to write assembler style C code.

PS: I removed the define just to make things more concise.

**Comment by schmurfy** [comment]
oups, sorry somehow I ended up posting on the wrong project xD

désolé :p

**Comment by schmurfy** [comment]
interesting project by the way :)
Too bad I can't remove the issue, feel free to do so if you can.

**Comment by Amaury** [comment]
No problem  :-)
