### ISSUE TITLE
multi-storage ?

### ISSUE THREAD

**Issue by mcarbonneaux** [Amaury/FineDB#4]
you tried to use LevelDB (from google, that already include snappy) in place of LMDB ?
https://github.com/google/leveldb

**Comment by Amaury** [comment]
I thought about it, but no I didn't. LMDB's benchmarks (http://symas.com/mdb/microbench/) are interresting. It seems that LevelDB is faster on writings but LMDB is a lot faster on reading operations.
My guess is that data are read more often then written.

**Comment by mcarbonneaux** [comment]
https://influxdb.com/blog/2014/06/20/leveldb_vs_rocksdb_vs_hyperleveldb_vs_lmdb_performance.html
sure that lmdb more faster on read ? on this benchmark is not so clear....
and http://symas.com/mdb/ondisk/ 

leveldb use natively snappy, that you've added on your server !

and not all need more read that write depend on application need...

this while be interesting to make plugable the storage engine...

**Comment by Amaury** [comment]
Maybe. I'll take a look at the complexity, because each engine has different functionnalities and a different API...
