### ISSUE TITLE
Potential data race in nn_mutex_lock () and nn_global_term()

### ISSUE THREAD

**Issue by ITWOI** [Amaury/FineDB#5]
Hi all,

Our bug scanner has reported a data race issue at [mutex.c#L71](https://github.com/Amaury/FineDB/blob/master/lib/nanomsg/src/utils/mutex.c#L71) and [global.c#L241.](https://github.com/Amaury/FineDB/blob/master/lib/nanomsg/src/core/global.c#L241)

Followings are code snippets.

```c++
void nn_mutex_lock (struct nn_mutex *self)
{
    int rc;

    rc = pthread_mutex_lock (&self->mutex);
    errnum_assert (rc == 0, rc);
}
```

and

```c++
static void nn_global_term (void)
{
#if defined NN_HAVE_WINDOWS
    int rc;
#endif
    struct nn_list_item *it;
    struct nn_transport *tp;

    /*  If there are no sockets remaining, uninitialise the global context. */
    nn_assert (self.socks);
```

The race occurs when the two asserts failed, causing two threads accessing *stderr* simultaneously.
here is one possible call trace:
global.c:321->global.c:229->pool.c:30->worker_posix.inc:109->thread_posix.c:55->thread_posix.c:44->worker_posix.inc:194->mutex.c:71; global.c:325->global.c:241

SourceBrella Inc.,
Yu

**Comment by Amaury** [comment]
Thanks for your bug report.

These two files are in the nanomsg library. It should be reported to the maintainer of this project.
FineDB will be updated with a more recent version of nanomsg.

**Comment by ITWOI** [comment]
Hi,

We have checked nanomsg library, the bug is not reported in the current version.

SourceBrella Inc.,
Yu
